### ISSUE TITLE
Rename "plairekt" to "plailect" .zip

### ISSUE THREAD

**Issue by curtisy1** [jorgev259/wiiusetup#1]
Don't know if this is a typo or intentional, but I think the correct name would be plailect. Not a biggie, so I thought I make a new issue instead of a pull request, but if you want, I can hotfix this ASAP.

Nice work btw. :)

**Comment by jorgev259** [comment]
fixed **https://github.com/rikumax25/3SDSetup/commit/bfecdfcb359bcb76ddbbdb0a1f2ceb6a0345f2ba**
