### ISSUE TITLE
New Nintendont update


### ISSUE THREAD

**Issue by iGom** [jorgev259/wiiusetup#33]
Nintendont needs to be updated in the pack to the bulid 6.492 from 28th February, it got an important update for Super Smash Bros Gamecube Controller

https://github.com/FIX94/Nintendont/pull/868

https://github.com/FIX94/Nintendont/commit/eae81294b4f701612f2f467676310c54c614e5c2

**Comment by ghost** [comment]
Updated Nintendont in latest PR along with a Wiiflow setting change.
https://github.com/jorgev259/wiiusetup/pull/35
